[project]
name = "text-simplifier"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.14.3",
    "datasets>=4.5.0",
    "requests>=2.32.5",
    "tqdm>=4.67.3",
    "trafilatura>=2.0.0",
]
